spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Root@123
    url: jdbc:mysql://localhost:3306/housie
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        diaclet: org.hibernate.diaclet.MySQL5Dialect
    show-sql: true

logging:
  file:
    name: d:/logs/application-debug.log
  level:
    org:
      springframework: DEBUG
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

  devtools:
    restart:
      enabled: true

